# Generated by Django 5.0.6 on 2024-06-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0003_blogpost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_img',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='description',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='github_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='profile_image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='published_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='reactions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='reading_time_minutes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='twitter_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='url',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='website_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
